# Generated by Django 2.0.3 on 2018-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaprueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
