# Generated by Django 2.0.4 on 2018-04-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaprueba', '0002_product_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
    ]
